### PR TITLE
Adding strings.xml for German translation

### PR DESCRIPTION
**Pull request by clairekardas**
German translation

### CODE REVIEW

**Comment by TonnyL** [comment]
@christopherkardas 

Nice job!

**Comment by clairekardas** [comment]
@TonnyL appreciate it! Awesome app you've created there! 🙂

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TonnyL** [comment]
@christopherkardas 

Thanks for your job. The Mango App will be available on Google Play in the next two weeks. And your name will be displayed on the readme file of this repo.

BTW, I using OnePlus 3 and FastHub too🌚.

**Comment by clairekardas** [comment]
@TonnyL aww thanks. Mine is btw the OnePlus 3T, running Resurrection Remix (I'm moderator for the project 🤗)

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TonnyL** [comment]
@christopherkardas 
You deserve it.  And you are a ROM developer? That's awesome👍.

**Pull request merged**
