### PR TITLE
Translate to Vietnamese

### PR DESCRIPTION
**Pull request by ldhnam**

### CODE REVIEW

**Comment by TonnyL** [comment]
Nice job!

**Comment by ldhnam** [comment]
@TonnyL thank you! I will adopt Dagger 2

**Comment by TonnyL** [comment]
@ldhnam 
Ah... You could fork it and adapt dagger. But I want to do it by myself cause I have not used dagger yet and I want to try it😂.

**Comment by ldhnam** [comment]
@TonnyL OK, I will not adopt Dagger

**Comment by TonnyL** [comment]
@ldhnam 
Thanks for your translation job! That's cool. And your name will be displayed on the readme file of the repo.

**Comment by ldhnam** [comment]
@TonnyL Thank you very much

**Pull request merged**
